// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghrmjxghxifbkhpmtcwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdocm1qeGdoeGlmYmtocG10Y3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MzgxOTUsImV4cCI6MjA0OTQxNDE5NX0.HXHyJm5fkIiRmv3GBU5XJQy7rN6QvCFmyZbx6ccat7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);